version: '2.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1#

  # cms:
  #   image: cms:latest
  #   ports:
  #     - 443:443
  #     - 80:80

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    # https://github.com/Azure/Azurite
    ports:
      - "10000:10000" # blob
      - "10001:10001" # queue
      - "10002:10002" # table

  #redis:
  #  image: redis:4-alpine
  #  container_name: edi-redis
  #  command: [ "redis-server", "--bind", "0.0.0.0", "--port", "6379" ]
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #  hostname: redis
  #  ports:
  #    - '6379:6379'
  #  restart: on-failure