name: home-server
services:
    registry:
        restart: always
        container_name: registry
        volumes:
            - ${path}/certs:/certs
        environment:
            - REGISTRY_HTTP_ADDR=0.0.0.0:443
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/client.crt
            - REGISTRY_HTTP_TLS_KEY=/certs/client.key
        ports:
            - 443:443
        image: registry:latest
